sudo: required
services:
    - docker
    
before_install:
    - docker build -t guslegge/docker-react -f Dockerfile.dev .
    
script:
    - docker run guslegge/docker-react npm run test -- --coverage
    
    
# In the upcoming lecture, we will be adding a script to our .travis.yml file. Due to a change in how the Jest library works with Create React App, we need to make a small modification:
# 
# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage
#  
# instead should be:
# 
# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test
# Additionally, you may want to set the following property to the top of your .travis.yml file:
# 
#  language: generic 